Repository typedb/typedb-behaviour, pull requests merged in 2020-05, with the labels that each got.

#40 Explanation Behaviour Test Updates
  behaviour/graql/reasoner/explanation.feature
Labels: priority: high

#38 Graql Delete Scenarios
  .github/CODEOWNERS
  behaviour/graql/language/define.feature
  behaviour/graql/language/delete.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
  behaviour/graql/language/undefine.feature
Labels: priority: high, type: feature

#45 Add axiomatic 'define' tests
  behaviour/graql/language/define.feature
Labels: priority: medium, type: refactor
