Repository typedb/typedb-behaviour, pull requests merged in 2020-07, with the labels that each got.

#67 Resolution testing
  behaviour/resolution/reasoner/BUILD
  behaviour/resolution/reasoner/reasoner.feature
Labels: priority: high, type: feature

#73 Update resolution BDD syntax for clarity
  behaviour/resolution/reasoner/reasoner.feature
Labels: priority: high, type: refactor

#74 Fix reasoner tests failing due to changed steps
  behaviour/resolution/reasoner/reasoner.feature
Labels: type: bug

#70 Migrate reasoner attribute attachment & value predicate ITs to BDD
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/reasoner.feature
  behaviour/graql/reasoner/resolution.feature
  behaviour/graql/reasoner/resolution/BUILD
  behaviour/graql/reasoner/resolution/attribute-attachment.feature
  behaviour/graql/reasoner/resolution/value-predicate.feature
Labels: type: feature

#78 Migrate Type Generation & Hierarchy Reasoner tests to Resolution BDDs
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/resolution.feature
  behaviour/graql/reasoner/resolution/BUILD
  behaviour/graql/reasoner/resolution/attribute-attachment.feature
  behaviour/graql/reasoner/resolution/test-framework.feature
  behaviour/graql/reasoner/resolution/type-generation.feature
  behaviour/graql/reasoner/resolution/type-hierarchy.feature
  behaviour/graql/reasoner/resolution/value-predicate.feature
  behaviour/graql/reasoner/rule-validation.feature
Labels: priority: medium, type: feature

#80 Clean up artifact depending on tests
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.snapshot
  tools/BUILD
Labels: priority: high, type: build

#79 Migrate Concept Inequality and Variable Role ITs to resolution BDD
  behaviour/graql/reasoner/resolution/BUILD
  behaviour/graql/reasoner/resolution/concept-inequality.feature
  behaviour/graql/reasoner/resolution/type-hierarchy.feature
  behaviour/graql/reasoner/resolution/variable-role.feature
Labels: priority: medium, type: feature

#77 Uncomment resolution steps that have been fixed by changes to the test framework
  behaviour/graql/reasoner/resolution/attribute-attachment.feature
  behaviour/graql/reasoner/resolution/value-predicate.feature
Labels: priority: low, type: feature

#81 Migrate ReasoningIT to BDD
  behaviour/graql/language/BUILD
  behaviour/graql/language/define.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
  behaviour/graql/language/rule-validation.feature
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/attribute-attachment.feature
  behaviour/graql/reasoner/concept-inequality.feature
  behaviour/graql/reasoner/negation.feature
  behaviour/graql/reasoner/relation-inference.feature
  behaviour/graql/reasoner/resolution-test-framework.feature
  behaviour/graql/reasoner/resolution.feature
  behaviour/graql/reasoner/resolution/BUILD
  behaviour/graql/reasoner/roleplayer-attachment.feature
  behaviour/graql/reasoner/type-generation.feature
  behaviour/graql/reasoner/type-hierarchy.feature
  behaviour/graql/reasoner/value-predicate.feature
  behaviour/graql/reasoner/variable-roles.feature
Labels: priority: medium, type: feature

#82 Migrate OntologicalQueryIT to BDD
  behaviour/graql/language/match.feature
  behaviour/graql/language/rule-validation.feature
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/schema-queries.feature
  behaviour/graql/reasoner/test-framework.feature
Labels: priority: medium, type: feature

#83 Fix roles being used in multiple relations
  behaviour/graql/language/define.feature
  behaviour/graql/reasoner/concept-inequality.feature
  behaviour/graql/reasoner/type-generation.feature
  behaviour/graql/reasoner/variable-roles.feature
Labels: priority: medium, type: bug

#84 Unignore tests that were skipped due to attribute value conversions
  behaviour/graql/language/insert.feature
Labels: type: refactor
