Repository typedb/typedb-behaviour, pull requests merged in 2020-10, with the labels that each got.

#103 Update to new rule syntax
  graql/explanation/reasoner.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/roleplayer-attachment.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-generation.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: priority: high, type: refactor

#104 Unignore client-java tests that were segfaulting
  graql/language/insert.feature
Labels: priority: medium, type: refactor

#106 Rule interaction test
  graql/reasoner/BUILD
  graql/reasoner/rule-interaction.feature
Labels: type: feature

#110 Update to Graql and Concept behaviours
  concept/rule/rule.feature
  concept/thing/attribute.feature
  concept/thing/entity.feature
  concept/thing/relation.feature
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
  connection/database.feature
  connection/session.feature
  connection/transaction.feature
  graql/explanation/language.feature
  graql/explanation/reasoner.feature
  graql/language/compute.feature
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/get.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/roleplayer-attachment.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-generation.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: priority: medium, type: feature

#107 Rule testing updated to reflect new rule conclusion restrictions
  graql/language/rule-validation.feature
  graql/reasoner/BUILD
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/roleplayer-attachment.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-generation.feature
  graql/reasoner/type-hierarchy.feature
Labels: type: feature

#111 fix syntax issues
  graql/reasoner/rule-interaction.feature
Labels: type: feature
