Repository typedb/typedb-behaviour, pull requests merged in 2020-12, with the labels that each got.

#114 Add tests for defining cyclic schema graphs
  graql/language/define.feature
Labels: priority: high, type: feature

#113 Integrate dependency-analysis job
  .grabl/automation.yml
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: type: build

#116 Remove server cleanup steps
  concept/thing/attribute.feature
  concept/thing/entity.feature
  concept/thing/relation.feature
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
  connection/database.feature
  connection/session.feature
  connection/transaction.feature
  graql/explanation/language.feature
  graql/explanation/reasoner.feature
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/get.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
  graql/reasoner/arithmetic-equality.feature
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: type: feature

#117 Build remotely on Ubuntu 20.04
  .bazelrc
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#122 Test that attribute type hierarchies can be redefined
  graql/language/define.feature
Labels: priority: high, type: bug

#121 Make concept map validation steps more concise
  connection/database.feature
  connection/session.feature
  connection/transaction.feature
  graql/explanation/language.feature
  graql/explanation/reasoner.feature
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/get.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
Labels: type: refactor

#125 Insert and match inherited roles tests
  graql/language/match.feature
Labels: type: bug
