Repository typedb/typedb-behaviour, pull requests merged in 2020-06, with the labels that each got.

#43 Remove all usages of implicit concepts
  behaviour/graql/language/define.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/undefine.feature
  dependencies/graknlabs/dependencies.bzl
  tools/operator/RoleGeneraliseOperator.java
Labels: priority: high, type: refactor

#48 New graql language tests: define and mutate
  behaviour/graql/language/BUILD
  behaviour/graql/language/define.feature
  behaviour/graql/language/delete.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/mutate.feature
  behaviour/graql/language/undefine.feature
Labels: priority: high, type: feature

#50 Merge mutate tests into define.feature
  behaviour/graql/language/BUILD
  behaviour/graql/language/define.feature
  behaviour/graql/language/mutate.feature
Labels: priority: high, type: refactor

#51 Add PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: priority: low, type: documentation

#52 Add Graql Get, Match and Undefine scenario drafts
  behaviour/graql/language/define.feature
  behaviour/graql/language/get.feature
  behaviour/graql/language/match.feature
  behaviour/graql/language/undefine.feature
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/resolution.feature
Labels: priority: high, type: refactor

#53 Migrate Graql Define IT tests to BDD
  behaviour/graql/language/define.feature
Labels: priority: low, type: refactor

#57 Update graknlabs dependencies to use ones that use gRPC 1.29.0
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  tools/integrity/Validator.java
Labels: priority: blocker, type: build

#58 Migrate Graql Match/Get tests to BDD
  behaviour/graql/language/BUILD
  behaviour/graql/language/get.feature
  behaviour/graql/language/match.feature
Labels: priority: medium, type: feature

#59 Improve Graql Match tests
  behaviour/graql/language/match.feature
Labels: priority: medium, type: feature

#55 Migrate Graql Insert tests to BDD
  behaviour/graql/language/insert.feature
Labels: priority: medium, type: feature

#54 Migrate Graql Delete ITs to BDD
  behaviour/graql/language/delete.feature
  behaviour/graql/language/get.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/reasoner/resolution.feature
Labels: priority: medium, type: feature

#62 Depend on @graknlabs_dependencies
  .bazelrc
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  tools/integrity/BUILD
  tools/integrity/test/BUILD
  tools/operator/BUILD
  tools/operator/test/BUILD
Labels: x: do not merge

#61 Migrate Graql Undefine ITs to BDD
  behaviour/graql/language/define.feature
  behaviour/graql/language/undefine.feature
Labels: priority: medium, type: feature

#66 Update tests to reflect that [2] and [2] are no longer considered as distinct values of a `double`
  behaviour/graql/language/insert.feature
Labels: priority: medium, type: feature

#68 Remove bazel-deps
  WORKSPACE
  dependencies/graknlabs/dependencies.bzl
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts/ch/qos/logback/BUILD
  dependencies/maven/artifacts/com/google/code/findbugs/BUILD
  dependencies/maven/artifacts/com/google/errorprone/BUILD
  dependencies/maven/artifacts/com/google/guava/BUILD
  dependencies/maven/artifacts/com/google/j2objc/BUILD
  dependencies/maven/artifacts/net/bytebuddy/BUILD
  dependencies/maven/artifacts/org/codehaus/mojo/BUILD
  dependencies/maven/artifacts/org/mockito/BUILD
  dependencies/maven/artifacts/org/objenesis/BUILD
  dependencies/maven/artifacts/org/slf4j/BUILD
  dependencies/maven/dependencies.bzl
  dependencies/maven/dependencies.yaml
  dependencies/maven/update.sh
  tools/integrity/BUILD
  tools/integrity/test/BUILD
  tools/operator/BUILD
  tools/operator/test/BUILD
Labels: type: build

#64 Migrate axiomatic tests to BDD
  behaviour/graql/language/delete.feature
  behaviour/graql/language/get.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
Labels: priority: medium, type: feature

#71 Ignore two tests that depend on doubles inserted as longs working
  behaviour/graql/language/insert.feature
Labels: type: bug
