Repository typedb/typedb-behaviour, pull requests merged in 2020-08, with the labels that each got.

#87 Rename keyspace to database
  behaviour/concept/thing/attribute.feature
  behaviour/concept/thing/entity.feature
  behaviour/concept/thing/relation.feature
  behaviour/concept/type/attributetype.feature
  behaviour/concept/type/entitytype.feature
  behaviour/concept/type/relationtype.feature
  behaviour/concept/type/thingtype.feature
  behaviour/connection/BUILD
  behaviour/connection/database.feature
  behaviour/connection/session.feature
  behaviour/connection/transaction.feature
  behaviour/graql/explanation/language.feature
  behaviour/graql/explanation/reasoner.feature
  behaviour/graql/language/define.feature
  behaviour/graql/language/delete.feature
  behaviour/graql/language/get.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
  behaviour/graql/language/rule-validation.feature
  behaviour/graql/language/undefine.feature
  behaviour/graql/reasoner/attribute-attachment.feature
  behaviour/graql/reasoner/concept-inequality.feature
  behaviour/graql/reasoner/negation.feature
  behaviour/graql/reasoner/relation-inference.feature
  behaviour/graql/reasoner/resolution-test-framework.feature
  behaviour/graql/reasoner/roleplayer-attachment.feature
  behaviour/graql/reasoner/schema-queries.feature
  behaviour/graql/reasoner/test-framework.feature
  behaviour/graql/reasoner/type-generation.feature
  behaviour/graql/reasoner/type-hierarchy.feature
  behaviour/graql/reasoner/value-predicate.feature
  behaviour/graql/reasoner/variable-roles.feature
  tools/integrity/Validator.java
  tools/integrity/test/ValidatorIT.java
Labels: priority: high

#85 Migrate RecursionIT, and materialisation tests from TransactionIT, to BDD
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/recursion.feature
  behaviour/graql/reasoner/relation-inference.feature
Labels: priority: medium, type: feature

#86 Migrate NegationIT to BDD
  behaviour/graql/language/define.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
  behaviour/graql/language/rule-validation.feature
  behaviour/graql/reasoner/negation.feature
Labels: priority: medium, type: feature

#88 Migrate Client-Java IT from Core
  behaviour/connection/keyspace.feature
  behaviour/connection/transaction.feature
  behaviour/graql/language/define.feature
Labels: priority: high, type: refactor

#92 Merge 2.0 into master
  behaviour/connection/database.feature
  behaviour/connection/transaction.feature
  behaviour/graql/language/define.feature
  behaviour/graql/language/insert.feature
  behaviour/graql/language/match.feature
  behaviour/graql/language/rule-validation.feature
  behaviour/graql/reasoner/BUILD
  behaviour/graql/reasoner/negation.feature
  behaviour/graql/reasoner/recursion.feature
  behaviour/graql/reasoner/relation-inference.feature
Labels: priority: blocker, type: refactor

#90 Uncomment attribute value type override test
  behaviour/graql/language/define.feature
Labels: priority: low, type: feature

#95 In Concept BDDs, don't commit transactions after error steps v2
  behaviour/concept/thing/entity.feature
  behaviour/concept/type/entitytype.feature
  behaviour/connection/database.feature
Labels: priority: medium, type: bug

#97 Clean up bazel WORKSPACE dependencies
  WORKSPACE
Labels: priority: high, type: build

#98 Refactor: clean up to use 2.0 build dependencies
  .bazelrc
  .circleci/config.yml
  WORKSPACE
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  tools/BUILD
  tools/operator/BUILD
Labels: type: build

#99 Update Concept Type tests to support Core 2.0 and Client Java 2.0, and delete 'tools' package
  .bazelrc
  .bazelversion
  .circleci/config.yml
  .github/CODEOWNERS
  .grabl/automation.yml
  WORKSPACE
  behaviour/concept/type/attributetype.feature
  behaviour/concept/type/relationtype.feature
  dependencies/graknlabs/artifacts.bzl
  dependencies/graknlabs/repositories.bzl
  dependencies/maven/artifacts.bzl
  dependencies/maven/artifacts.snapshot
  dependencies/maven/update.sh
  tools/BUILD
  tools/integrity/BUILD
  tools/integrity/IntegrityException.java
  tools/integrity/RejectDuplicateSet.java
  tools/integrity/SemanticSet.java
  tools/integrity/Type.java
  tools/integrity/Validator.java
  tools/integrity/schema/AbstractTypes.java
  tools/integrity/schema/Has.java
  tools/integrity/schema/Plays.java
  tools/integrity/schema/Relates.java
  tools/integrity/schema/Sub.java
  tools/integrity/schema/TransitiveSub.java
  tools/integrity/test/BUILD
  tools/integrity/test/SemanticSets.java
  tools/integrity/test/ValidatorIT.java
  tools/integrity/test/ValidatorSetConstruction.java
  tools/integrity/test/logback.xml
  tools/operator/BUILD
  tools/operator/GeneraliseAttributeOperator.java
  tools/operator/IdFuzzyingOperator.java
  tools/operator/IdentityOperator.java
  tools/operator/Operator.java
  tools/operator/Operators.java
  tools/operator/PropertyVariableTransform.java
  tools/operator/RemoveRelationOperator.java
  tools/operator/RemoveRoleplayerOperator.java
  tools/operator/RemoveSubstitutionOperator.java
  tools/operator/RoleGeneraliseOperator.java
  tools/operator/TypeContext.java
  tools/operator/TypeGeneraliseOperator.java
  tools/operator/Utils.java
  tools/operator/VariableFuzzyingOperator.java
  tools/operator/range/NumberRange.java
  tools/operator/range/Range.java
  tools/operator/range/Ranges.java
  tools/operator/test/BUILD
  tools/operator/test/MockTypeContext.java
  tools/operator/test/OperatorTest.java
Labels: priority: high, type: bug
