Repository typedb/typedb-behaviour, pull requests merged in 2021-04, with the labels that each got.

#187 Unignore some tests
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/value-predicate.feature
Labels: priority: medium, type: refactor

#188 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/REFACTOR.md
Labels: type: refactor

#192 Add match scenario that fails due to traversal bug
  graql/language/match.feature
Labels: type: refactor

#193 Add rule value conversion validation scenarios
  graql/language/rule-validation.feature
Labels: priority: high, type: feature

#194 Add scenario to ensure relation subtypes can introduce new roles
  graql/language/define.feature
Labels: priority: medium

#195 Make match-by-key ownership test more precise
  graql/language/match.feature
Labels: priority: medium, type: feature

#196 Add scenario with contradicting iid and type
  graql/language/match.feature
Labels: priority: high, type: feature
