Repository typedb/typedb-behaviour, pull requests merged in 2021-02, with the labels that each got.

#159 Test disjunction with only different values
  graql/language/match.feature
Labels: priority: high, type: feature

#163 Reopen transaction to identify concepts
  graql/language/insert.feature
Labels: type: bug

#158 Update recursion feature to 2.0 syntax
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
Labels: type: refactor

#165 Remove Unrelated Insertion Scenario
  graql/language/update.feature
Labels: priority: high, type: bug

#166 Fix "Last Roleplayer" Scenario
  graql/language/update.feature
Labels: priority: high, type: bug

#168 Repair delete identifiers
  graql/language/delete.feature
Labels: type: bug

#167 Update Reasoning BDD for 2.0
  graql/reasoner/BUILD
  graql/reasoner/arithmetic-equality.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: type: refactor

#170 Correct ordering of operations in insert scenario
  graql/language/insert.feature
Labels: type: bug

#171 Add variable roles match query
  graql/language/match.feature
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/concept-inequality.feature
Labels: priority: medium, type: feature

#173 Fixes for reasoner tests
  graql/reasoner/BUILD
  graql/reasoner/compound-queries.feature
  graql/reasoner/value-predicate.feature
Labels: type: bug, type: feature

#174 Test deleting nonexistent DB in Core and Cluster
  connection/database.feature
Labels: priority: medium, type: feature

#175 Unignore negation scenarios
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/value-predicate.feature
Labels: priority: high, type: bug, type: refactor

#176 Refactor code to work with latest @graknlabs_dependencies
  WORKSPACE
  dependencies/graknlabs/repositories.bzl
Labels: priority: high, type: build

#179 Use self-hosted Bazel cache
  .bazelrc
Labels: priority: high, type: build, type: feature

#178 Update for default-on reasoner
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/compound-queries.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: type: feature

#181 Add scenario to test negation on a filtered out variable
  graql/language/match.feature
Labels: priority: medium, type: feature
