Repository typedb/typedb-behaviour, pull requests merged in 2021-01, with the labels that each got.

#128 Fix not reopening transaction after assert throws
  graql/language/match.feature
Labels: type: bug

#132 Ignore failing BDD test and fix typo
  connection/database.feature
Labels: type: bug

#133 Ignore failing BDD test in client-java
  connection/session.feature
Labels: type: bug

#135 Convert key ownership to regular ownership
  graql/language/define.feature
Labels: type: feature

#136 Bump year in license headers to 2021
  .bazelrc
  .gitignore
  .grabl/automation.yml
  BUILD
  WORKSPACE
  concept/BUILD
  concept/rule/BUILD
  concept/rule/rule.feature
  concept/thing/BUILD
  concept/thing/attribute.feature
  concept/thing/entity.feature
  concept/thing/relation.feature
  concept/type/BUILD
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
  connection/BUILD
  connection/database.feature
  connection/session.feature
  connection/transaction.feature
  dependencies/graknlabs/BUILD
  dependencies/graknlabs/repositories.bzl
  graql/analytics/BUILD
  graql/explanation/BUILD
  graql/explanation/language.feature
  graql/explanation/reasoner.feature
  graql/language/BUILD
  graql/language/compute.feature
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/get.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
  graql/reasoner/BUILD
  graql/reasoner/arithmetic-equality.feature
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: type: build

#138 Make steps that override 'plays' refer to the overridden type by scoped label
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  connection/database.feature
  connection/session.feature
Labels: priority: medium, type: bug

#140 Split 'graql match' step into aggregate, group, etc.
  graql/explanation/language.feature
  graql/explanation/reasoner.feature
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/get.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
Labels: priority: high, type: bug

#142 Temporarily disable all failing Graql Define tests
  graql/language/define.feature
  graql/language/match.feature
Labels: priority: medium, type: refactor

#143 Temporarily ignore failing Define test
  graql/language/define.feature
Labels: priority: low, type: bug

#144 Re-enabled Fixed Define Test
  graql/language/define.feature
Labels: type: bug

#147 Add scenario to test overriding roles in plays
  graql/language/define.feature
Labels: priority: medium, type: feature

#148 Add scenario to test overriding shadowed roles in plays
  graql/language/define.feature
Labels: priority: medium, type: feature

#149 Fix undefine feature tests
  graql/language/undefine.feature
Labels: priority: medium, type: bug

#150 Fix EntityType no-op scenario
  concept/type/entitytype.feature
  graql/language/undefine.feature
Labels: priority: medium, type: bug

#152 Split transaction test scenarios that causes wrong exception to be thrown
  connection/transaction.feature
Labels: type: bug

#153 Reenable remote build caching
  .bazelrc
Labels: type: build

#155 Remove unused integrity validation steps
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/get.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
Labels: priority: medium, type: refactor

#154 Update delete testing scenarios to reflect grakn 2.0
  connection/transaction.feature
  graql/language/delete.feature
Labels: priority: high, type: bug, type: feature

#156 Update reasoning BDD for 2.0 - part 1
  graql/reasoner/arithmetic-equality.feature
  graql/reasoner/attribute-attachment.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/negation.feature
  graql/reasoner/recursion.feature
  graql/reasoner/relation-inference.feature
  graql/reasoner/resolution-test-framework.feature
  graql/reasoner/rule-interaction.feature
  graql/reasoner/schema-queries.feature
  graql/reasoner/type-hierarchy.feature
  graql/reasoner/value-predicate.feature
  graql/reasoner/variable-roles.feature
Labels: priority: high, type: refactor

#157 Fix Transaction test throwing wrong error
  connection/transaction.feature
Labels: priority: high, type: bug
