Repository typedb/typedb-behaviour, pull requests merged in 2021-03, with the labels that each got.

#177 Fix ignore tags broken by comments
  graql/language/delete.feature
  graql/language/match.feature
  graql/reasoner/concept-inequality.feature
  graql/reasoner/value-predicate.feature
Labels: type: documentation

#184 Update rule validation scenarios
  graql/language/rule-validation.feature
Labels: priority: high, type: refactor

#183 Unignore tests that should now pass
  graql/language/define.feature
  graql/language/delete.feature
  graql/language/insert.feature
  graql/language/match.feature
  graql/language/rule-validation.feature
  graql/language/undefine.feature
Labels: priority: medium, type: refactor

#182 Fix unsatisfiable reasoning query
  graql/reasoner/concept-inequality.feature
Labels: priority: high, type: bug

#185 Extra test cases for determining rule stratifiability
  graql/language/rule-validation.feature
Labels: priority: medium, type: feature

#186 Fix Graql Get exception tests not working properly
  graql/language/get.feature
Labels: priority: medium, type: bug
