Repository typedb/typedb-behaviour, pull requests merged in 2022-11, with the labels that each got.

#231 Invert tests for key uniqueness across subtypes
  typeql/language/insert.feature
Labels: type: bug, priority: high

#232 Update tests for disjunctions in rules
  typeql/language/rule-validation.feature
  typeql/reasoner/attribute-attachment.feature
Labels: type: feature

#233 Update invalid reasoner test in attribute-attachment
  typeql/reasoner/attribute-attachment.feature
Labels: type: bug
