Repository typedb/typedb-behaviour, pull requests merged in 2023-10, with the labels that each got.

#264 Create a small representative suite of driver query tests
  connection/user.feature
  driver/BUILD
  driver/query.feature
  query/explanation/BUILD
  query/explanation/language.feature
  query/explanation/reasoner.feature
  query/language/BUILD
  query/language/define.feature
  query/language/delete.feature
  query/language/expression.feature
  query/language/get.feature
  query/language/insert.feature
  query/language/match.feature
  query/language/rule-validation.feature
  query/language/undefine.feature
  query/language/update.feature
  query/reasoner/BUILD
  query/reasoner/attribute-attachment.feature
  query/reasoner/compound-queries.feature
  query/reasoner/concept-inequality.feature
  query/reasoner/negation.feature
  query/reasoner/recursion.feature
  query/reasoner/relation-inference.feature
  query/reasoner/rule-interaction.feature
  query/reasoner/schema-queries.feature
  query/reasoner/type-hierarchy.feature
  query/reasoner/value-predicate.feature
  query/reasoner/variable-roles.feature
  typeql/analytics/BUILD
Labels: type: feature, priority: high

#265 Disallow explicit use of role type aliases
  query/language/define.feature
  query/language/insert.feature
  query/language/match.feature
  query/language/rule-validation.feature
  query/language/undefine.feature
  query/reasoner/recursion.feature
Labels: type: refactor, priority: high

#266 Add test for variable role types traversed in either direction
  query/language/match.feature
Labels: type: bug
