Repository typedb/typedb-behaviour, pull requests merged in 2023-04, with the labels that each got.

#243 Ensure exception is thrown when redefining attribute with a different value type
  typeql/language/define.feature
Labels: type: bug

#241 Types referenced in rules cannot be undefined
  typeql/language/undefine.feature
Labels: type: bug

#244 Refactor connection open syntax and remove usage of 'And'
  concept/serialization/json.feature
  concept/thing/attribute.feature
  concept/thing/entity.feature
  concept/thing/relation.feature
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
  connection/database.feature
  connection/session.feature
  connection/transaction.feature
  connection/user.feature
  typeql/explanation/language.feature
  typeql/explanation/reasoner.feature
  typeql/language/define.feature
  typeql/language/delete.feature
  typeql/language/get.feature
  typeql/language/insert.feature
  typeql/language/match.feature
  typeql/language/rule-validation.feature
  typeql/language/undefine.feature
  typeql/language/update.feature
  typeql/reasoner/attribute-attachment.feature
  typeql/reasoner/compound-queries.feature
  typeql/reasoner/concept-inequality.feature
  typeql/reasoner/negation.feature
  typeql/reasoner/recursion.feature
  typeql/reasoner/relation-inference.feature
  typeql/reasoner/rule-interaction.feature
  typeql/reasoner/schema-queries.feature
  typeql/reasoner/type-hierarchy.feature
  typeql/reasoner/value-predicate.feature
  typeql/reasoner/variable-roles.feature
Labels: type: refactor, priority: high

#245 Test that root types cannot be deleted
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
Labels: type: feature, priority: medium

#246 Refactor connection open step syntax
  concept/serialization/json.feature
  concept/thing/attribute.feature
  concept/thing/entity.feature
  concept/thing/relation.feature
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
  connection/database.feature
  connection/session.feature
  connection/transaction.feature
  typeql/explanation/language.feature
  typeql/explanation/reasoner.feature
  typeql/language/define.feature
  typeql/language/delete.feature
  typeql/language/get.feature
  typeql/language/insert.feature
  typeql/language/match.feature
  typeql/language/rule-validation.feature
  typeql/language/undefine.feature
  typeql/language/update.feature
  typeql/reasoner/attribute-attachment.feature
  typeql/reasoner/compound-queries.feature
  typeql/reasoner/concept-inequality.feature
  typeql/reasoner/negation.feature
  typeql/reasoner/recursion.feature
  typeql/reasoner/relation-inference.feature
  typeql/reasoner/rule-interaction.feature
  typeql/reasoner/schema-queries.feature
  typeql/reasoner/type-hierarchy.feature
  typeql/reasoner/value-predicate.feature
  typeql/reasoner/variable-roles.feature
Labels: type: refactor, priority: high

#247 Add test: connected user can be retrieved
  connection/user.feature
Labels: type: feature, priority: high
