Repository typedb/typedb-behaviour, pull requests merged in 2023-09, with the labels that each got.

#257 Test that overlapping deletes do not fail
  typeql/language/delete.feature
Labels: type: feature, type: refactor, priority: high

#258 All role types from abstract relation types are concrete and inheritable
  concept/type/relationtype.feature
Labels: type: refactor, priority: high

#260 Remove root Thing type from concept BDD tests
  concept/type/BUILD
  concept/type/attributetype.feature
  concept/type/entitytype.feature
  concept/type/relationtype.feature
  concept/type/thingtype.feature
  connection/user.feature
  typeql/language/define.feature
Labels: type: feature, x: do not merge

#261 Fix: ref attribute must be owned as @key
  typeql/language/match.feature
Labels: type: bug, priority: blocker

#262 Rename Client to Driver throughout
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  connection/database.feature
  connection/user.feature
  typeql/explanation/language.feature
  typeql/explanation/reasoner.feature
  typeql/language/define.feature
Labels: type: refactor, priority: blocker
