Repository typedb/typedb-behaviour, pull requests merged in 2025-03, with the labels that each got.

#345 Add tests for precedence and associativity of arithmetic operators
  query/language/expression.feature
Labels: type: documentation

#343 Test multiple expression assignments in different branches
  query/language/expression.feature
Labels: type: feature

#346 Add behaviour tests for 'put'
  query/language/BUILD
  query/language/put.feature
Labels: type: feature

#355 Test nested negation inputs
  query/language/negation.feature
Labels: priority: blocker

#354 Add regression tests for various fixes around variable usage
  query/functions/usage.feature
  query/language/expression.feature
  query/language/pipelines.feature
Labels: type: bug
